/* 
 ***** CRS - Car Rental System (Sistema de Locadora de Veículos) *****
 *********************** Script SQL (SQLite) *************************
 * Author: Marcos Willian de Souza                                   *
 * Date:   12/04/2025                                                *
 *********************************************************************
*/

PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS TB_USER;
DROP TABLE IF EXISTS TB_CLIENT;
DROP TABLE IF EXISTS TB_AUTOMAKER;
DROP TABLE IF EXISTS TB_MODEL;
DROP TABLE IF EXISTS TB_CATEGORY;
DROP TABLE IF EXISTS TB_TYPE;
DROP TABLE IF EXISTS TB_VEHICLE;
DROP TABLE IF EXISTS TB_RENTAL_DATA;
DROP TABLE IF EXISTS TB_RENTAL;
DROP TABLE IF EXISTS TB_RETURN;
DROP TABLE IF EXISTS TB_VEHICLE_DESREGISTRATION;

PRAGMA foreign_keys=ON;

CREATE TABLE TB_USER(
    USER_ID INTEGER CONSTRAINT PK_USER PRIMARY KEY AUTOINCREMENT NOT NULL,
    USER_NAME VARCHAR(512),
    USER_LOGIN VARCHAR(100) UNIQUE,
    USER_PASSWORD VARCHAR(512) NOT NULL,
    USER_ADMINISTRATOR BOOLEAN NOT NULL DEFAULT 0,
    USER_ACTIVE BOOLEAN NOT NULL DEFAULT 0,
    USER_RESET_PASSWORD BOOLEAN NOT NULL DEFAULT 0,
    USER_DELETE BOOLEAN NOT NULL DEFAULT 1
    );

CREATE TABLE TB_CLIENT(
    CLIENT_ID INTEGER CONSTRAINT PK_CLIENTE PRIMARY KEY AUTOINCREMENT NOT NULL,
    CLIENT_NAME VARCHAR(512) NOT NULL,
    CLIENT_TYPE VARCHAR(10) NOT NULL,
    CLIENT_CPF_CNPJ VARCHAR(20) UNIQUE,
    CLIENT_FONE VARCHAR(10) NOT NULL,
    CLIENT_CELLPHONE VARCHAR(11) NOT NULL,
    CLIENT_EMAIL VARCHAR(100) NOT NULL,
    CLIENT_ADDRESS_ZIPCODE VARCHAR(8) NOT NULL,
    CLIENT_ADDRESS_STREET VARCHAR(512) NOT NULL,
    CLIENT_ADDRESS_NUMBER VARCHAR(10) NOT NULL,
    CLIENT_ADDRESS_NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CLIENT_ADDRESS_STATE VARCHAR(100) NOT NULL,
    CLIENT_ADDRESS_UF VARCHAR(2) NOT NULL,
    CLIENT_REGISTRATION_DATE DATE NOT NULL,
    CLIENT_NOTES TEXT,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID)
    );
    
CREATE TABLE TB_AUTOMAKER(
    AUTOMAKER_ID INTEGER CONSTRAINT PK_AUTOMAKER PRIMARY KEY AUTOINCREMENT NOT NULL,
    AUTOMAKER_NAME VARCHAR(512) UNIQUE
    );

CREATE TABLE TB_MODEL(
    MODEL_ID INTEGER CONSTRAINT PK_MODEL PRIMARY KEY AUTOINCREMENT NOT NULL,
    MODEL_NAME VARCHAR(512) UNIQUE,
    AUTOMAKER_ID INTEGER NOT NULL,
    CONSTRAINT FK_AUTOMAKER FOREIGN KEY(AUTOMAKER_ID) REFERENCES TB_AUTOMAKER(AUTOMAKER_ID)
    );

CREATE TABLE TB_CATEGORY(
    CATEGORY_ID INTEGER CONSTRAINT PK_CATEGORY PRIMARY KEY AUTOINCREMENT NOT NULL,
    CATEGORY_NAME VARCHAR(512) UNIQUE
    );

CREATE TABLE TB_TYPE(
    TYPE_ID INTEGER CONSTRAINT PK_TYPE PRIMARY KEY AUTOINCREMENT NOT NULL,
    TYPE_NAME VARCHAR(512) UNIQUE
    );
	
CREATE TABLE TB_VEHICLE(
    VEHICLE_ID INTEGER CONSTRAINT PK_VEHICLE PRIMARY KEY AUTOINCREMENT NOT NULL,
    VEHICLE_DESCRIPTION VARCHAR(512),
    VEHICLE_PLATE VARCHAR(10) UNIQUE, 
    VEHICLE_COLOR VARCHAR(20),
    VEHICLE_YEAR VARCHAR(10),
    VEHICLE_REGISTRATION_DATE DATE NOT NULL,
    VEHICLE_NOTES TEXT,
    VEHICLE_STATUS VARCHAR(100) NOT NULL,
    VEHICLE_RENTED BOOLEAN NOT NULL DEFAULT 0,
    MODEL_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    TYPE_ID INTEGER NOT NULL,
    CONSTRAINT FK_MODEL FOREIGN KEY(MODEL_ID) REFERENCES TB_MODEL(MODEL_ID),
    CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_TYPE FOREIGN KEY(TYPE_ID) REFERENCES TB_TYPE(TYPE_ID)
    );
 
CREATE TABLE TB_RENTAL_DATA(
    RENTAL_DATA_ID INTEGER CONSTRAINT PK_RENTAL_DATA PRIMARY KEY AUTOINCREMENT NOT NULL,
    RENTAL_DATA_NAME VARCHAR(10) UNIQUE,
    RENTAL_DATA_DAILY_PRICE DOUBLE NOT NULL,
    RENTAL_DATA_DAILY_FINE_AMOUNT DOUBLE NOT NULL,
    MODEL_ID INTEGER NOT NULL,
    CONSTRAINT FK_MODEL FOREIGN KEY(MODEL_ID) REFERENCES TB_MODEL(MODEL_ID)
    );
 

CREATE TABLE TB_RENTAL(
    RENTAL_ID INTEGER CONSTRAINT PK_RENTAL PRIMARY KEY AUTOINCREMENT NOT NULL,
    RENTAL_RENTAL_DATE DATE NOT NULL,
    RENTAL_RETURN_DATE DATE NOT NULL,
    RENTAL_TOTAL_VALUE DOUBLE NOT NULL,
    RENTAL_NOTES TEXT,
    RENTAL_STATUS VARCHAR(100) NOT NULL,
    VEHICLE_ID INTEGER NOT NULL,
    CLIENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    RENTAL_DATA_ID INTEGER NOT NULL,
    CONSTRAINT FK_VEHICLE FOREIGN KEY(VEHICLE_ID) REFERENCES TB_VEHICLE(VEHICLE_ID),
    CONSTRAINT FK_CLIENT FOREIGN KEY(CLIENT_ID) REFERENCES TB_CLIENT(CLIENT_ID),
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID),
    CONSTRAINT FK_RENTAL_DATA FOREIGN KEY(RENTAL_DATA_ID) REFERENCES TB_RENTAL_DATA(RENTAL_DATA_ID)
    );
	
CREATE TABLE TB_RETURN(
    RETURN_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RETURN_DATE DATE NOT NULL,
    RETURN_TOTAL_DAILY_FINE DOUBLE NOT NULL,
    RETURN_NOTES TEXT,
    RENTAL_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_RENTAL FOREIGN KEY(RENTAL_ID) REFERENCES TB_RENTAL(RENTAL_ID),
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID)
    );
	
CREATE TABLE TB_VEHICLE_DESREGISTRATION(
    VEHICLE_DESREGISTRATION_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    VEHICLE_DESREGISTRATION_DATE DATE NOT NULL,
    VEHICLE_DESREGISTRATION_REASON TEXT NOT NULL,
    VEHICLE_DESREGISTRATION_NOTES TEXT,
    VEHICLE_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_VEHICLE FOREIGN KEY(VEHICLE_ID) REFERENCES TB_VEHICLE(VEHICLE_ID),
    CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID)
    );
    

INSERT INTO TB_USER(USER_NAME, USER_LOGIN, USER_PASSWORD, USER_ADMINISTRATOR, USER_ACTIVE, USER_RESET_PASSWORD, USER_DELETE)
    VALUES('Admin','admin','4b8c17321cbf7cdd28d0b563531aab6567642bc19b5d63d72dd0eb0b16498708a6cf4399b67bc09bfa8870f697fecae874f080ca90aaf0a323d561c739b1874b',1,1,0,0);
    
INSERT INTO TB_USER(USER_NAME, USER_LOGIN, USER_PASSWORD, USER_ADMINISTRATOR, USER_ACTIVE, USER_RESET_PASSWORD)
    VALUES('Default','default','110f64a86d6360eea03a9a9072412c83e855b0d80d9d58b30ac6d13ecefcccf6578aeadd09382159c5b1722f75cabe1fe99001a88959348fa75b86afeac8c769',0,1,0);

INSERT INTO TB_USER(USER_NAME, USER_LOGIN, USER_PASSWORD, USER_ADMINISTRATOR, USER_ACTIVE, USER_RESET_PASSWORD)
    VALUES('Marcos','marcos','607d439fbf841979298849bb5ab4ee8a7ed2b2f7ce445ffa37bbd43e7b76694e605ac2da36e503e45a3e29906ff4f168e4af5303cb4f4ab5b6dae22ff6c7d066',1,1,0);
    
INSERT INTO TB_USER(USER_NAME, USER_LOGIN, USER_PASSWORD, USER_ADMINISTRATOR, USER_ACTIVE, USER_RESET_PASSWORD)
    VALUES('Inativo','inativo','9371eb3c87ffe0774e5060f7b5a53d1f306c50a62ee84e95dc8f5d2772bd870e514fa240c17ee21f1028cebbd5b62a491f2de99b108e20285f92332856ac7d2c',1,0,0);
    
INSERT INTO TB_USER(USER_NAME, USER_LOGIN, USER_PASSWORD, USER_ADMINISTRATOR, USER_ACTIVE, USER_RESET_PASSWORD)
    VALUES('Reset','reset','beca20cb71eff80dfe74fe1c6b1b05b4df5ea5c46ac87c63520581f0aad3eb995bd92a7b812c4bf8299ff3b3ea333a81e73acc4427a5cbf831cabec265c14b95',0,1,1);
    
SELECT * FROM TB_USER;

    